name: Nightly Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Artifact
        run: bash ./tools/build.sh
      
      - uses: actions/upload-artifact@v4
        with:
          path: ./
